Repository TokTok/hs-msgpack-rpc-conduit, pull requests merged in 2021-12, with the labels that each got.

#46 perf: Use StrictData for all modules that define data types.
  .cirrus.yml
  src/Network/MessagePack/Capabilities.hs
  src/Network/MessagePack/Client/Internal.hs
  src/Network/MessagePack/Interface.hs
  src/Network/MessagePack/Rpc.hs
  src/Network/MessagePack/Server/Basic.hs
  src/Network/MessagePack/Types/Error.hs
  src/Network/MessagePack/Types/Result.hs
  src/Network/MessagePack/Types/Server.hs
Labels: performance

#43 chore(deps): loosen dependency restriction on "network" to <3.1
  msgpack-rpc-conduit.cabal
Labels: dependencies

#42 docs: Update readme to better reflect the repo split.
  .github/settings.yml
  .restyled.yaml
  README.md
Labels: documentation

#47 chore: Use toktok-stack 0.0.23 for cirrus builds.
  .cirrus.yml
Labels: chore
